"""uqff_registry_status — R5 status-report generator (Unified Registry Program).

Reads uqff_registry_primitives + UNIFIED_REGISTRY.csv → emits
UNIFIED_REGISTRY_STATUS_REPORT.md and UNIFIED_REGISTRY_RESULTS_TABLE.md/.csv.

STATUS: v0.2.0 scaffold. Empty inputs → empty outputs. This module is
populated by the v0.3.0+ wiring campaign as each PAPER_N whitepaper is
read, its derivation extracted, and one row added to UNIFIED_REGISTRY.csv.

Discipline (locked, from predecessor Star-Magic v5.86.0 R3 program,
PAPER_2130):
    - Idempotent: two consecutive runs produce byte-identical output.
    - Read-only inputs. Reserved-name outputs only.
    - Values computed LIVE from primitives; no rounded decimals stored.
    - Every row cites a PAPER_N provenance.
"""
from __future__ import annotations

import csv
from typing import Any


REGISTRY_CSV = "UNIFIED_REGISTRY.csv"
RESULTS_TABLE_CSV = "UNIFIED_REGISTRY_RESULTS_TABLE.csv"
RESULTS_TABLE_MD = "UNIFIED_REGISTRY_RESULTS_TABLE.md"
STATUS_REPORT_MD = "UNIFIED_REGISTRY_STATUS_REPORT.md"


def _load_registry_rows() -> list[dict[str, Any]]:
    """Load UNIFIED_REGISTRY.csv into row dicts. v0.2.0: empty."""
    try:
        with open(REGISTRY_CSV, "r", encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))
    except FileNotFoundError:
        return []


def _derived_constant_rows() -> list[tuple]:
    """Return canonical derived-constant tuples for the results table.

    Format: (constant_name, canonical_route, closed_form, uqff_value,
             reference, reference_kind, residual_pct).

    v0.2.0: empty. Filled row-by-row as papers get wired.
    """
    return []


def calculate_status_report(dataset: dict | None = None) -> dict:
    """Public surface — compute the R5 status report."""
    rows = _load_registry_rows()
    return {
        "value": {
            "registry_rows": len(rows),
            "derived_constants_live": len(_derived_constant_rows()),
            "status": "SCAFFOLD_v0.2.0_AWAITING_WIRING",
        }
    }


def write_results_table_csv() -> None:
    """Emit UNIFIED_REGISTRY_RESULTS_TABLE.csv."""
    rows = _derived_constant_rows()
    with open(RESULTS_TABLE_CSV, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["constant", "canonical_route", "closed_form",
                    "uqff_value", "reference", "reference_kind",
                    "residual_pct"])
        for r in rows:
            w.writerow(r)


def write_results_table_md() -> None:
    """Emit UNIFIED_REGISTRY_RESULTS_TABLE.md."""
    with open(RESULTS_TABLE_MD, "w", encoding="utf-8", newline="\n") as f:
        f.write("# UNIFIED_REGISTRY_RESULTS_TABLE.md — preprint results table (R5)\n\n")
        f.write("Generated by `uqff_registry_status.py` (idempotent).\n\n")
        f.write("v0.2.0 SCAFFOLD: no derived constants wired yet. Populated by v0.3.0+ campaign.\n")


def write_status_report_md() -> None:
    """Emit UNIFIED_REGISTRY_STATUS_REPORT.md."""
    with open(STATUS_REPORT_MD, "w", encoding="utf-8", newline="\n") as f:
        f.write("# UNIFIED_REGISTRY_STATUS_REPORT.md — R5 program status\n\n")
        f.write("Generated by `uqff_registry_status.py::main()` (idempotent).\n\n")
        f.write("v0.2.0 SCAFFOLD: registry has header-only files. No rows wired yet.\n")


def main() -> None:
    write_results_table_csv()
    write_results_table_md()
    write_status_report_md()


if __name__ == "__main__":
    main()
