"""registry_generator — regeneration source-of-truth for the Unified Registry Program.

Reads:
    uqff_registry_primitives.py       canonical constants
    whitepapers/PAPER_N_*.md          physics content

Emits (idempotent, reserved-name outputs):
    UNIFIED_REGISTRY.csv                  master registry (one row per quantity)
    UNIFIED_REGISTRY_MERGED.csv           duplicate-collapsed view
    UNIFIED_REGISTRY_DUPLICATES.csv       collision detector
    UNIFIED_REGISTRY_GAPS.csv             observables in whitepapers not in registry
    UNIFIED_REGISTRY_R1_QUEUE.csv         adjudication queue
    UNIFIED_REGISTRY_R2_MAPPING.csv       mapping-round output
    UNIFIED_REGISTRY_R3_LEDGER.csv        canonicalization ledger
    UNIFIED_REGISTRY_CORPUS_CITATIONS.csv PAPER_N provenance
    UNIFIED_REGISTRY_SCHEMA.md            column definitions
    UNIFIED_REGISTRY_VERSION.txt          per-ship marker

STATUS: v0.2.0 scaffold. Empty inputs (no wired papers yet) → empty outputs
(header-only CSVs). The regen chain is populated as each PAPER_N is wired
via the v0.3.0+ campaign.

Discipline (locked, from predecessor Star-Magic v5.86.0 R0-R5 program,
PAPER_2130):
    - Idempotent regeneration (two consecutive runs → byte-identical outputs).
    - Read-only inputs.
    - Reserved-name outputs only.
    - Every row cites a PAPER_N.
    - No hardcoded numeric literals; every value flows from primitives.
"""
from __future__ import annotations

import csv
import datetime
import hashlib
import os
import sys


REGISTRY_CSV = "UNIFIED_REGISTRY.csv"
MERGED_CSV = "UNIFIED_REGISTRY_MERGED.csv"
DUPLICATES_CSV = "UNIFIED_REGISTRY_DUPLICATES.csv"
GAPS_CSV = "UNIFIED_REGISTRY_GAPS.csv"
R1_QUEUE_CSV = "UNIFIED_REGISTRY_R1_QUEUE.csv"
R2_MAPPING_CSV = "UNIFIED_REGISTRY_R2_MAPPING.csv"
R3_LEDGER_CSV = "UNIFIED_REGISTRY_R3_LEDGER.csv"
CORPUS_CITATIONS_CSV = "UNIFIED_REGISTRY_CORPUS_CITATIONS.csv"
SCHEMA_MD = "UNIFIED_REGISTRY_SCHEMA.md"
VERSION_TXT = "UNIFIED_REGISTRY_VERSION.txt"


def _scan_whitepapers() -> list[str]:
    """Return the sorted list of PAPER_N .md files in whitepapers/."""
    if not os.path.isdir("whitepapers"):
        return []
    return sorted(f for f in os.listdir("whitepapers") if f.endswith(".md"))


def _build_registry_rows() -> list[dict]:
    """Return one row per registered quantity.

    Columns (17): quantity, origin, kind, canonical_route, formula, value,
    reference, residual_pct, sector, phi_variant, paper_source, confirmations,
    py_sites, cpp_sites, lean_sites, corpus_citations, status.

    v0.2.0: empty. Populated during v0.3.0+ wiring.
    """
    return []


def _detect_duplicates(rows: list[dict]) -> list[tuple]:
    return []


def _detect_gaps(rows: list[dict], papers: list[str]) -> list[tuple]:
    return []


def write_registry_csv() -> None:
    rows = _build_registry_rows()
    cols = ["quantity", "origin", "kind", "canonical_route", "formula",
            "value", "reference", "residual_pct", "sector", "phi_variant",
            "paper_source", "confirmations", "py_sites", "cpp_sites",
            "lean_sites", "corpus_citations", "status"]
    with open(REGISTRY_CSV, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def write_version_txt(ship_version: str = "0.2.0") -> None:
    """Emit UNIFIED_REGISTRY_VERSION.txt — the per-ship provenance marker."""
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(VERSION_TXT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# UQFF Star-Magic-Program Registry Version Marker\n")
        f.write(f"# Regenerated by uqff v{ship_version} at {ts}\n")
        f.write("#\n")
        f.write("# This file forces per-ship registry provenance in git.\n")
        f.write("# Every ship's regen chain emits this marker with the current\n")
        f.write("# pyproject.toml version and UTC timestamp.\n")
        f.write("#\n")
        f.write(f"SHIP_VERSION: {ship_version}\n")
        f.write(f"GENERATED_AT: {ts}\n")
        f.write("GENERATOR: registry_generator.py + uqff_registry_status.py + "
                "uqff_registry_graph.py + uqff_registry_xgeo.py\n")


def write_schema_md() -> None:
    with open(SCHEMA_MD, "w", encoding="utf-8", newline="\n") as f:
        f.write("# UNIFIED_REGISTRY_SCHEMA.md — Master Registry column definitions\n\n")
        f.write("Generated by `registry_generator.py` (idempotent).\n\n")
        f.write("v0.2.0 SCAFFOLD: schema defined; registry has header-only rows.\n")


def main() -> None:
    write_registry_csv()
    write_version_txt()
    write_schema_md()


if __name__ == "__main__":
    main()
