"""uqff_registry_graph — R4 falsifiability graph builder (Unified Registry Program).

Emits (idempotent, read-only inputs):
    UNIFIED_REGISTRY_GRAPH.csv         edge list: primitive→constant, primitive→row, constant→paper
    UNIFIED_REGISTRY_FALSIFIABILITY.md per-primitive break report

STATUS: v0.2.0 scaffold. Empty registry → empty graph → empty falsifiability
report. Populated by v0.3.0+ campaign as each PAPER_N is wired.

Discipline (from predecessor Star-Magic v5.86.0 R3/R4 program, PAPER_2130):
    - Idempotent regeneration.
    - Read-only inputs.
    - Reserved-name outputs only.
    - Every edge cites a paper.
"""
from __future__ import annotations

import csv


GRAPH_CSV = "UNIFIED_REGISTRY_GRAPH.csv"
FALSIFIABILITY_MD = "UNIFIED_REGISTRY_FALSIFIABILITY.md"
REGISTRY_CSV = "UNIFIED_REGISTRY.csv"


def _build_edges() -> list[tuple[str, str, str, str, str]]:
    """Return graph edges as (src_kind, src, dst_kind, dst, edge_info).

    v0.2.0: empty. Populated as papers get wired into the registry.
    """
    return []


def write_graph_csv() -> None:
    """Emit UNIFIED_REGISTRY_GRAPH.csv."""
    with open(GRAPH_CSV, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["src_kind", "src", "dst_kind", "dst", "edge_info"])
        for e in _build_edges():
            w.writerow(e)


def write_falsifiability_md() -> None:
    """Emit UNIFIED_REGISTRY_FALSIFIABILITY.md."""
    with open(FALSIFIABILITY_MD, "w", encoding="utf-8", newline="\n") as f:
        f.write("# UNIFIED_REGISTRY_FALSIFIABILITY.md — R4 per-primitive break report\n\n")
        f.write("Generated by `uqff_registry_graph.py` (idempotent).\n\n")
        f.write("v0.2.0 SCAFFOLD: no edges yet. If primitive X were revised, nothing breaks\n")
        f.write("because nothing is wired. Populated by v0.3.0+ campaign.\n")


def main() -> None:
    write_graph_csv()
    write_falsifiability_md()


if __name__ == "__main__":
    main()
